---
- name: Deploy WAR file to Remote Machines in Container
  hosts: all
  become: yes

  tasks:
    - name: Stop existing container
      shell: docker stop 8am_java_webapp_container
      ignore_errors: yes

    - name: Remove existing container
      shell: docker rm 8am_java_webapp_container
      ignore_errors: yes

    - name: Pull latest Docker image
      shell: docker pull dipanshur/8am_java_webapp_image

    - name: Run Docker container
      shell: >
        docker run -d
        --name 8am_java_webapp_container
        -p 1234:8080
        dipanshur/8am_java_webapp_image